# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Libraries/Ila_Lib/Ctrl_Ila/Ctrl_Ila.xci
# IP: The module: 'Ctrl_Ila' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Libraries/Ila_Lib/Ctrl_Ila/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ctrl_Ila'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Libraries/Ila_Lib/Ctrl_Ila/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ctrl_Ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Libraries/Ila_Lib/Ctrl_Ila/Ctrl_Ila_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ctrl_Ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Libraries/Ila_Lib/Ctrl_Ila/Ctrl_Ila.xci
# IP: The module: 'Ctrl_Ila' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Libraries/Ila_Lib/Ctrl_Ila/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ctrl_Ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Libraries/Ila_Lib/Ctrl_Ila/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ctrl_Ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Libraries/Ila_Lib/Ctrl_Ila/Ctrl_Ila_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ctrl_Ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
