# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param simulator.questaInstallPath C:/CaeTools/QuestaSim/win64
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Projects/A_Series_7/LvdsSourceSync/Xapp585/VhdlVersion/Vivado/Xapp585Vhdl/Xapp585Vhdl.cache/wt [current_project]
set_property parent.project_path C:/Projects/A_Series_7/LvdsSourceSync/Xapp585/VhdlVersion/Vivado/Xapp585Vhdl/Xapp585Vhdl.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Projects/A_Series_7/LvdsSourceSync/Xapp585/VhdlVersion/Vivado/Xapp585Vhdl/Xapp585Vhdl.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Projects/A_Series_7/LvdsSourceSync/Xapp585/VhdlVersion/Libraries/delay_controller_wrap.vhd
  C:/Projects/A_Series_7/LvdsSourceSync/Xapp585/VhdlVersion/Libraries/gearbox_4_to_7.vhd
  C:/Projects/A_Series_7/LvdsSourceSync/Xapp585/VhdlVersion/Libraries/gearbox_4_to_7_slave.vhd
  C:/Projects/A_Series_7/LvdsSourceSync/Xapp585/VhdlVersion/Libraries/n_x_serdes_1_to_7_mmcm_idelay_ddr.vhd
  C:/Projects/A_Series_7/LvdsSourceSync/Xapp585/VhdlVersion/Libraries/serdes_1_to_7_mmcm_idelay_ddr.vhd
  C:/Projects/A_Series_7/LvdsSourceSync/Xapp585/VhdlVersion/Libraries/serdes_1_to_7_slave_idelay_ddr.vhd
  C:/Projects/A_Series_7/LvdsSourceSync/Xapp585/VhdlVersion/Vhdl/top5x2_7to1_ddr_rx.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Projects/A_Series_7/LvdsSourceSync/Xapp585/VhdlVersion/Constraints/top5x2_7to1_ddr_rx.xdc
set_property used_in_implementation false [get_files C:/Projects/A_Series_7/LvdsSourceSync/Xapp585/VhdlVersion/Constraints/top5x2_7to1_ddr_rx.xdc]


synth_design -top top5x2_7to1_ddr_rx -part xc7k325tffg900-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top5x2_7to1_ddr_rx.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top5x2_7to1_ddr_rx_utilization_synth.rpt -pb top5x2_7to1_ddr_rx_utilization_synth.pb"
