# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Constraints/Xapp585_RxTx_LPC_LA_02Mar18.xdc

# XDC: C:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Constraints/Xapp585_RxTx_Timing_05Mar18.xdc

# XDC: C:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Constraints/Xapp585_RxTx_BitStream_12Mar18.xdc

# IP: C:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Libraries/Ila_Lib/Ctrl_Ila/Ctrl_Ila.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Ctrl_Ila || ORIG_REF_NAME==Ctrl_Ila} -quiet] -quiet

# IP: C:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Libraries/Vio_Lib/Ctrl_Vio/Ctrl_Vio.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Ctrl_Vio || ORIG_REF_NAME==Ctrl_Vio} -quiet] -quiet
