# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param simulator.questaInstallPath C:/CaeTools/QuestaSim/win64
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Vivado/Xapp585Kc705/Xapp585Kc705.cache/wt [current_project]
set_property parent.project_path C:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Vivado/Xapp585Kc705/Xapp585Kc705.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Vivado/Xapp585Kc705/Xapp585Kc705.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library Transmitter_Lib {
  C:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Libraries/Transmitter_Lib/clock_generator_pll_7_to_1_diff_ddr.vhd
  C:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Libraries/Transmitter_Lib/serdes_7_to_1_diff_ddr.vhd
  C:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Libraries/Transmitter_Lib/n_x_serdes_7_to_1_diff_ddr.vhd
  C:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Libraries/Transmitter_Lib/Ddr_Tx_5x2_7to1.vhd
}
read_vhdl -library Osc_Control_Lib {
  C:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Libraries/Osc_Control_Lib/controller_top.vhd
  C:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Libraries/Osc_Control_Lib/kcpsm6.vhd
  C:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Libraries/Osc_Control_Lib/i2c_controller.vhd
}
read_vhdl -library Receiver_Lib {
  C:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Libraries/Receiver_Lib/delay_controller_wrap.vhd
  C:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Libraries/Receiver_Lib/gearbox_4_to_7.vhd
  C:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Libraries/Receiver_Lib/gearbox_4_to_7_slave.vhd
  C:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Libraries/Receiver_Lib/serdes_1_to_7_mmcm_idelay_ddr.vhd
  C:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Libraries/Receiver_Lib/serdes_1_to_7_slave_idelay_ddr.vhd
  C:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Libraries/Receiver_Lib/n_x_serdes_1_to_7_mmcm_idelay_ddr.vhd
}
read_vhdl -vhdl2008 -library xil_defaultlib {
  C:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Vhdl/TxRx_5x2_7to1_Toplevel.vhd
  C:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Vhdl/TxRx_5x2_7to1_Appslevel.vhd
}
read_ip -quiet C:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Libraries/Ila_Lib/Ctrl_Ila/Ctrl_Ila.xci
set_property used_in_synthesis false [get_files -all c:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Libraries/Ila_Lib/Ctrl_Ila/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Libraries/Ila_Lib/Ctrl_Ila/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Libraries/Ila_Lib/Ctrl_Ila/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Libraries/Ila_Lib/Ctrl_Ila/Ctrl_Ila_ooc.xdc]

read_ip -quiet C:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Libraries/Vio_Lib/Ctrl_Vio/Ctrl_Vio.xci
set_property used_in_implementation false [get_files -all c:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Libraries/Vio_Lib/Ctrl_Vio/Ctrl_Vio.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Libraries/Vio_Lib/Ctrl_Vio/Ctrl_Vio_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Constraints/Xapp585_RxTx_LPC_LA_02Mar18.xdc
set_property used_in_implementation false [get_files C:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Constraints/Xapp585_RxTx_LPC_LA_02Mar18.xdc]

read_xdc C:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Constraints/Xapp585_RxTx_Timing_05Mar18.xdc
set_property used_in_implementation false [get_files C:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Constraints/Xapp585_RxTx_Timing_05Mar18.xdc]

read_xdc C:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Constraints/Xapp585_RxTx_BitStream_12Mar18.xdc
set_property used_in_implementation false [get_files C:/Projects/A_Series_7/LvdsSourceSync/Xapp585/DdrVhdlVersion/Constraints/Xapp585_RxTx_BitStream_12Mar18.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top TxRx_5x2_7to1_Appslevel -part xc7k325tffg900-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef TxRx_5x2_7to1_Appslevel.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file TxRx_5x2_7to1_Appslevel_utilization_synth.rpt -pb TxRx_5x2_7to1_Appslevel_utilization_synth.pb"
