#--------------------------------------------------------------------------------------------
#-   ____  ____
#-  /   /\/   /
#- /___/  \  /
#- \   \   \/    © Copyright 2018 Xilinx, Inc. All rights reserved.
#-  \   \        This file contains confidential and proprietary information of Xilinx, Inc.
#-  /   /        and is protected under U.S. and international copyright and other
#- /___/   /\    intellectual property laws.
#- \   \  /
#-  \___\/\___
#-
#--------------------------------------------------------------------------------------------
#- Device:              7-Series, Zync
#- Author:              Defossez
#- Entity Name:         Xapp585_RxTx_Timing_<date>
#- Purpose:             Constraint file for reference design of XAPP585 ported on
#-                      a KC705 board. Transmitter and receiver pins are output on
#-                      the FMC LPC connector and used with the XM107 loopback board.
#-
#- Tools:               Vivado_2017.4 or higher
#- Limitations:         none
#-
#- Vendor:              Xilinx Inc.
#- Version:
#- Filename:            Xapp585_RxTx_Timing_<date>.xdc
#- Date Created:        Mar 2018
#- Date Last Modified:  Mar 2018
#--------------------------------------------------------------------------------------------
#- Disclaimer:
#-      This disclaimer is not a license and does not grant any rights to the materials
#-      distributed herewith. Except as otherwise provided in a valid license issued to you
#-      by Xilinx, and to the maximum extent permitted by applicable law: (1) THESE MATERIALS
#-      ARE MADE AVAILABLE "AS IS" AND WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL
#-      WARRANTIES AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING BUT NOT LIMITED
#-      TO WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR
#-      PURPOSE; and (2) Xilinx shall not be liable (whether in contract or tort, including
#-      negligence, or under any other theory of liability) for any loss or damage of any
#-      kind or nature related to, arising under or in connection with these materials,
#-      including for any direct, or any indirect, special, incidental, or consequential
#-      loss or damage (including loss of data, profits, goodwill, or any type of loss or
#-      damage suffered as a result of any action brought by a third party) even if such
#-      damage or loss was reasonably foreseeable or Xilinx had been advised of the
#-      possibility of the same.
#-
#- CRITICAL APPLICATIONS
#-      Xilinx products are not designed or intended to be fail-safe, or for use in any
#-      application requiring fail-safe performance, such as life-support or safety devices
#-      or systems, Class III medical devices, nuclear facilities, applications related to
#-      the deployment of airbags, or any other applications that could lead to death,
#-      personal injury, or severe property or environmental damage (individually and
#-      collectively, "Critical Applications"). Customer assumes the sole risk and
#-      liability of any use of Xilinx products in Critical Applications, subject only to
#-      applicable laws and regulations governing limitations on product liability.
#-
#- THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS PART OF THIS FILE AT ALL TIMES.
#-
#- Contact:    e-mail  hotline@xilinx.com        phone   + 1 800 255 7778
#---------------------------------------------------------------------------------------------
#- Revision History:
#-  Rev. -
#---------------------------------------------------------------------------------------------
#-
#---------------------------------------------------------------------------------------------
#- Global timing for a reference clock of 200MHz.
#---------------------------------------------------------------------------------------------
create_clock -add -name refclkin -period 5.000 [get_ports refclkin_p]
#---------------------------------------------------------------------------------------------
#- Timing for the DDR transmitter.
#- The clock input for the transmitter is generated by a KC705 onboard Si570 oscillator.
#- The default output frequency of that oscillator is 156 MHz (6.410 ns).
#- The constraint is set tighter, to 166 MHz!
#---------------------------------------------------------------------------------------------
create_clock    -add -name tx_freqgen -period 6.410 [get_ports tx_freqgen_p]
#-
#- Max delay between registers on the pixel_clock and registers on the tx_clk_d4 clock.
#- tx_pixel_clock is application and tx_clk_d4 is OSERDES and registers CLKDIV clock.
#- Max delay chosen for 250 MHz.
set_max_delay   -from   [get_clocks \
                            [list \
                                [get_clocks -of_objects \
                                    [get_pins */Txd/clkgen/loop*.tx_mmcm_adv_inst/CLKOUT0] \
                                ] \
                            ] \
                        ] \
                -to     [get_clocks \
                            [list \
                                [get_clocks -of_objects \
                                    [get_pins */Txd/clkgen/loop*.tx_mmcm_adv_inst/CLKOUT1] \
                                ] \
                            ]\
                        ] 4.0
#- Max delay between the registers capturing the sampled clock data from the ISERDESE2
#- and the pipeline register used for DCD conversion. All registers are clocked on the
#- rx_clk_d4 clock. Max delay chosen for 250 MHz
#-set_max_delay   -from [get_pins {*/Rxd/rx*/gb*/loop*[*].dataout_reg[*]/C}] \
#-                -to [get_pins {*/int_dcd_rx_clk_dataout_reg[*]/D}] 4.0
#---------------------------------------------------------------------------------------------
#- Timing for the DDR receiver
#---------------------------------------------------------------------------------------------
create_clock -add -name clkin1 -period 6.410 [get_ports clkin1_p]
#-
#- Need to ignore re-timing paths from pixel clock to clk_d4 through the gearbox
#-
#- Below constraints create warnings in synthesis but are applied during implementation.
set_false_path  -from [get_pins */*/*/gb*/loop*[*].ram_inst/RAM*/CLK] \
                -to [get_pins */*/*/gb*/loop*[*].dataout_reg[*]/D]
set_false_path  -from [get_pins */*/loop*.loop*[*].rxn/gb*/loop*[*].ram_inst/RAM*/CLK] \
                -to [get_pins */*/loop*.loop*[*].rxn/gb*/loop*[*].dataout_reg[*]/D]
#- Some domain change flip-flops
set_false_path  -to [get_pins -hier -filter {name =~ *rx*dom_ch*/D}]
set_false_path  -to [get_pins -hier -filter {name =~ *rx*dom_ch*/PRE}]
#- Path from clock input to clock input serdes
set_false_path  -from [get_ports clkin1_p] \
                -to [get_pins -hier -filter {name =~ *rx*iserdes_c?/DDLY}]
#---------------------------------------------------------------------------------------------
#- These constraints all have to do with the VIA and ILA devices in the design.
#- A design without these components doesn't need these constraints.
#-
#- Max delay from last FF registering signals from the receiver, on rx_clk_d4, to the
#- register in front of the VIO, on the refclk.
set_max_delay   -from [get_clocks -of_objects [get_pins */Rxd/rx*/loop*.rx_mmcm_adv_inst/CLKOUT1]] \
                -to [get_clocks refclkin] 5.0
#- ignore timing between teh gearbox output (data captured from the clock input) and the
#- register in front of the VIO.
set_false_path  -from [get_clocks -of_objects [get_pins */Rxd/rx*/loop*.rx_mmcm_adv_inst/CLKFBOUT]] \
                -to [get_clocks refclkin]
#-
#- Output from VIO, on refclk, to input of transmitter application FFs on tx_pixel_clock.
#- Load a static value in registers, timing ignored.
set_false_path  -from [get_clocks refclkin] \
                -to [get_clocks -of_objects [get_pins */*/clkgen/loop*.tx_mmcm_adv_inst/CLKFBOUT]]
#-
#- Signals between the rxclk_d4_int clock domain and teh rx_pixel_clock domain.
set_max_delay   -from [get_clocks -of_objects [get_pins */Rxd/rx*/loop*.rx_mmcm_adv_inst/CLKOUT1]] \
                -to [get_clocks -of_objects [get_pins */Rxd/rx*/loop*.rx_mmcm_adv_inst/CLKFBOUT]] 5.0
#-
#---------------------------------------------------------------------------------------------
#- The End .......
#---------------------------------------------------------------------------------------------
